# Generated by Django 4.2 on 2023-07-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_alter_product_description_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt',
            field=models.FileField(default=None, null=True, upload_to='orders/receipts/'),
        ),
    ]
