# Generated by Django 4.2 on 2023-05-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, max_length=100)),
                ('promocode', models.CharField(blank=True, max_length=8)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
