# Generated by Django 4.2 on 2023-06-20 19:09

from django.db import migrations, models
import myauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=myauth.models.profile_avatar_directory_path),
        ),
    ]
